version: '2'
services:
  PostgreSQL:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
  
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=fakenews_100k
    volumes:
      - ./db_dump:/db_dump
      - /srv/docker/postgresql:/var/lib/postgresql
